-- MySQL Script generated by MySQL Workbench
-- ter 22 fev 2022 15:59:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dioceses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dioceses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `id_bispo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `id_bispo_UNIQUE` (`id_bispo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paroquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paroquia` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `id_padre_responsavel` INT NOT NULL,
  `id_padre_auxiliar` INT NULL,
  `preve_historia` VARCHAR(1000) NULL,
  `Dioceses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Paroquia_Dioceses1_idx` (`Dioceses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Paroquia_Dioceses1`
    FOREIGN KEY (`Dioceses_id`)
    REFERENCES `mydb`.`Dioceses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comunidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comunidades` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `id_coodenador` VARCHAR(45) NOT NULL,
  `id_vice_coodenador` VARCHAR(45) NOT NULL,
  `id_tesoureiro` VARCHAR(45) NOT NULL,
  `preve_historia` VARCHAR(1000) NULL,
  `Paroquia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Comunidades_Paroquia1_idx` (`Paroquia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comunidades_Paroquia1`
    FOREIGN KEY (`Paroquia_id`)
    REFERENCES `mydb`.`Paroquia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dizimistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dizimistas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `Comunidades_id` INT NULL,
  `Paroquia_id` INT NOT NULL,
  `Dioceses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idDizimistas_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Dizimistas_Comunidades_idx` (`Comunidades_id` ASC) VISIBLE,
  INDEX `fk_Dizimistas_Paroquia1_idx` (`Paroquia_id` ASC) VISIBLE,
  INDEX `fk_Dizimistas_Dioceses1_idx` (`Dioceses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Dizimistas_Comunidades`
    FOREIGN KEY (`Comunidades_id`)
    REFERENCES `mydb`.`Comunidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dizimistas_Paroquia1`
    FOREIGN KEY (`Paroquia_id`)
    REFERENCES `mydb`.`Paroquia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dizimistas_Dioceses1`
    FOREIGN KEY (`Dioceses_id`)
    REFERENCES `mydb`.`Dioceses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
